version : '2'
services:
    #mongo db
    mongo:
        image : mongo:4.2.6
        ports: 
            - 27017:27017
    #front
    front:
        build: ./chatty_frontend
        volumes: 
            - ./chatty_frontend:/usr/src/app
        links: 
            - load-balancer
        ports: 
            - 5000:3000
        tty : true 
    #back1
    back1:
        build: ./chatty-nest
        tty: true
        depends_on :
            - mongo
        volumes: 
            - ./chatty-nest:/usr/src/app
        ports: 
            - 5001:3001
    #back2
    back2:
        build: ./chatty-nest
        tty: true
        depends_on :
            - mongo
        volumes: 
            - ./chatty-nest:/usr/src/app
        ports: 
            - 5002:3001
    #loadbalancer
    load-balancer:
        build: ./load_balancer
        links: 
            - back1 
            - back2
        ports: 
            - 8080:8080