version : '2'
services:
    #mongo db
    mongo:
        image : mongo:4.2.6
        ports: 
            - 27017:27017
    #front
    front:
        build: ./chatty_frontend
        volumes: 
            - ./chatty_frontend:/usr/src/app
        links: 
            - load-balancer
        ports: 
            - 3000:3000
        tty : true 
        command: ["npm", "run", "start"]
    #back1
    back1:
        build: ./chatty-nest
        tty: true
        depends_on :
            - mongo
        ports: 
            - 3001:3001
        command: ["npm", "run", "start"]
    #back2
    back2:
        build: ./chatty-nest
        tty: true
        depends_on :
            - mongo
        ports: 
            - 3002:3001
        command: ["npm", "run", "start"]
    #loadbalancer
    load-balancer:
        build: ./load_balancer
        links: 
            - back1 
            - back2
        ports: 
            - 80:80