version : '2'
services:
    #mongo db
    #front
    front:
        build: ./chatty_frontend
        volumes: 
            - ./chatty_frontend:/usr/src/app
        ports: 
            - 3000:3000
        tty : true 
    # #back1
    # back1:
    #     build: ./chatty-nest
    #     volumes: 
    #         - ./chatty-nest:/usr/src/app
    #     ports: 
    #         - 3001:3001
    # #back2
    # back2:
    #     build: ./chatty-nest
    #     volumes: 
    #         - ./chatty-nest:/usr/src/app
    #     ports: 
    #         - 3002:3001
    # #loadbalancer
    # load-balancer:
    #     build: ./load_balancer
    #     links: 
    #         - back1 
    #         - back2
    #     ports: 
    #         - 8080:8000